# Generated by Django 2.0.6 on 2018-11-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('media_url', models.CharField(blank=True, default='', max_length=1024)),
                ('asset_key', models.CharField(db_index=True, default='', max_length=80)),
                ('source', models.SmallIntegerField(choices=[(0, 'youtube'), (1, 'twitter'), (2, 'unknown')])),
                ('asset_type', models.SmallIntegerField(choices=[(0, 'video'), (1, 'audio')])),
                ('inlib_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'initial'), (1, 'started'), (2, 'finished'), (3, 'faield')], default=0)),
                ('update_at', models.DateField(blank=True, null=True)),
                ('link_url', models.ManyToManyField(to='analysis.SearchUrl')),
            ],
        ),
    ]
