# Generated by Django 2.0.6 on 2018-11-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.CharField(blank=True, default='', max_length=1024)),
                ('source', models.SmallIntegerField(choices=[(0, 'youtube'), (1, 'twitter'), (-1, '其他')])),
                ('asset_type', models.SmallIntegerField(choices=[(0, 'video'), (1, 'audio')])),
                ('in_lib', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('inlib_time', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
