# Generated by Django 2.0.6 on 2018-11-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraasset',
            name='source',
            field=models.SmallIntegerField(choices=[(0, 'youtube'), (1, 'twitter'), (2, 'unknown')]),
        ),
    ]
