# Generated by Django 2.0.6 on 2018-11-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20181113_0549'),
        ('data', '0002_auto_20181113_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraasset',
            old_name='original_url',
            new_name='media_url',
        ),
        migrations.AddField(
            model_name='extraasset',
            name='link_url',
            field=models.ManyToManyField(to='analysis.SearchUrl'),
        ),
    ]
