# Generated by Django 2.0.6 on 2018-11-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20181113_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraasset',
            name='visible',
        ),
        migrations.AddField(
            model_name='extraasset',
            name='asset_key',
            field=models.CharField(db_index=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='extraasset',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
