# Generated by Django 2.0.6 on 2018-11-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_url', models.CharField(blank=True, db_index=True, default='', max_length=1024)),
                ('source', models.SmallIntegerField(choices=[(0, 'youtube'), (1, 'twitter'), (-1, '其他')])),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
