# Generated by Django 2.0.6 on 2018-11-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_searchurl_fetch_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchurl',
            name='source',
            field=models.SmallIntegerField(choices=[(0, 'youtube'), (1, 'twitter'), (2, 'unknown')]),
        ),
    ]
