# Generated by Django 2.0.6 on 2018-11-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20181113_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchurl',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
